export const AppData = [
  "E-commerce application",
  "CRUD application",
  "Todo application",
  "Food delivery",
  "Simple Management system",
  "Complex management system",
  "Language translator",
  "Fitness tracking platform",
  "Chatbot",
  "Automation system (AI involved)",
  "Budgeting platform",
  "Social networking platform",
  "Travel related platform",
  "Chat app",
  "Calculator",
  "Blogging platform",
  "Authentication system",
  "API data fetch",
  "Portfolio / Personal website",
  "Job portal",
  "Real State platform",
  "Stock market platform",
  "Online learning platform",
  "Audio / Video Streaming app",
  "Gaming platform",
  "Booking System",
  "Crowdfunding platform",
  "Recommendation Platform (AI involved)",
  "Personalized suggestor (AI involved)",
  "Investment platform",
  "Event planning system",
];
